apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-container
        image: nest-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
